name: CI

on:
  push:
  pull_request:
    types:
    - synchronize
    - opened
    - closed
  workflow_dispatch:

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - "8.0.19"

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: pmmp/setup-php-action@247e08acd52c1465f8f144c162c88f079d8c1174
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"

      - name: Restore Composer package cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/composer"
          key: "php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: "php-${{ matrix.php }}-composer-"

      - name: Install PHPStan Composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyze
        # This possible to break jobs. 
        continue-on-error: true
 
    steps:
      - uses: actions/checkout@v3
      - run: make suitetest/cases/${{matrix.suite-name}} DIFF="diff -y" POCKETMINE_VERSION=${{matrix.pocketmine-version}}
  fix-cs:
    name: Fix Code Standard violations
    runs-on: ubuntu-latest
    if: "!contains(github.event_name, 'pull_request') || github.event.pull_request.merged"
    needs:
    - phpstan
    steps:
      - uses: actions/checkout@v3
      - uses: docker://oskarstark/php-cs-fixer-ga:latest
        with:
          args: --config=.php-cs-fixer.php --diff
      - name: Set cpr step parameters under pull request context
        id: cpr-param4pr
        if: contains(github.event_name, 'pull_request')
        run: |
          echo "Event context: ${{ github.event_name }}"
          echo "::set-output name=fixed::${{ github.base_ref }} after merging ${{ github.head_ref }}"
      - uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          base: ${{ github.base_ref || '' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Apply php-cs-fixer changes as of ${{ github.sha }}
          title: Fix coding standards in ${{ steps.cpr-param4pr.outputs.fixed || github.ref }}
          branch: php-cs-fixer/${{ github.sha }}
          delete-branch: true
          assignees: ${{ github.actor }}
          body: |
            Please apply these changes on the ${{ github.base_ref || github.ref }} branch to fix coding standard violations.
      - uses: thollander/actions-comment-pull-request@v1
        if: contains(github.event_name, 'pull_request') && steps.cpr.outputs.pull-request-number
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Thank you for your contribution!
            @${{ github.event.pull_request.user.login }} Your changes are reformatted in #${{ steps.cpr.outputs.pull-request-number }} to assimilate with the repository's code style and standard.
